apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: webapps.integreatly.org
spec:
  group: integreatly.org
  names:
    kind: WebApp
    listKind: WebAppList
    plural: webapps
    singular: webapp
    shortNames:
      - wa
  scope: Namespaced
  versions: 
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                app_label:
                  type: string
                template:
                  type: object
                  properties:
                    path:
                      type: string
                    parameters:
                      type: object        
      additionalPrinterColumns:
        - name: status
          description: webapp current status
          type: string
          jsonPath: .status.message
        - name: created
          description: webapp date creation
          type: date
          jsonPath: .metadata.creationTimestamp
