apiVersion: apps/v1
kind: Deployment
metadata:
  name: tutorial-web-app-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tutorial-web-app-operator
  template:
    metadata:
      labels:
        name: tutorial-web-app-operator
    spec:
      serviceAccountName: tutorial-web-app-operator
      containers:
        - name: tutorial-web-app-operator
          image: quay.io/redhatintegration/tutorial-web-app-operator:v0.0.63-workshop
          ports:
            - containerPort: 60000
              name: metrics
          command:
            - tutorial-web-app-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "tutorial-web-app-operator"
